### PR TITLE
update sass linting rules

### PR DESCRIPTION
**Pull request by planktonic**
Updates the two sass lint configuration files with new rules on property ordering — instead of alphabetical, we now order by type.

e.g. positional properties are grouped together & text properties together, with layout properties coming first, visual styles coming later.

### CODE REVIEW

**Comment by pmeinhardt** [comment]
Hey hey @planktonic, @SonniesEdge, do you still have this on your map?

Just checking, because logo-quest would probably be affected too if we decide to update the sass-lint config there. Though maybe it makes sense to only apply this new config to any new projects/long-running projects?

**Comment by SonniesEdge** [comment]
@pmeinhardt Personally, I'd only apply it to new projects. I can't see a need to apply the new rules to Logoquest.

**Comment by planktonic** [comment]
@pmeinhardt What charlie said — this is not a breaking or terribly important change that we need to roll out to all projects

**Comment by pmeinhardt** [comment]
Cool. Thanks to both of you for your feedback.

**Pull request merged**
